### PR TITLE
Drop buildbot patches. Allow org member to access buildbot.

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Mic92** [comment]
Needs https://github.com/NixOS/nixpkgs/pull/272376

**Comment by zowoq** [comment]
If we could have a way of adding pythonPackages here as well as extraConfig could drop the prometheus stuff entirely?

**Comment by Mic92** [comment]
Probably.

**Comment by zowoq** [comment]
pythonPackages is set here?

```nix
      pythonPackages = ps: [
        ps.requests
        ps.treq
        ps.psycopg2
        (ps.toPythonModule pkgs.buildbot-worker)
        pkgs.buildbot-plugins.www-react
        (pkgs.python3.pkgs.callPackage ../default.nix { })
      ] ++ lib.optional (cfg.prometheusExporterPort != null)
        (ps.buildPythonPackage rec {
          pname = "buildbot-prometheus";
          version = "0c81a89bbe34628362652fbea416610e215b5d1e";
          src = pkgs.fetchFromGitHub {
            owner = "claws";
            repo = "buildbot-prometheus";
            rev = version;
            hash = "sha256-bz2Nv2RZ44i1VoPvQ/XjGMfTT6TmW6jhEVwItPk23SM=";
          };
          propagatedBuildInputs = [ ps.prometheus-client ];
          doCheck = false;
        });
    };
```

**Comment by Mic92** [comment]
Mhm is pythonPackages not accumulative? I'll check.

**Pull request merged**
