### PR TITLE
Move skipped builds to local worker

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by zowoq** [comment]
@Mic92 While watching builds being processed it looks like the skipped builds aren't parallelized?

**Comment by MagicRB** [comment]
https://github.com/buildbot/buildbot/blob/c6dc292f38d0353d33215f8809c617afa47e11a6/master/buildbot/worker/base.py#L645 according to here the worker should be able to attach to multiple builders. We don't set `max_builds` our selves. I'll try to experiment with this and see if i can get it parallel.

**Comment by zowoq** [comment]
Thanks.

I remembered that the lix fork did something with the skipped builds, they actually removed it, not sure if that is relevant here or not.

https://git.lix.systems/lix-project/buildbot-nix/commit/156e6e3deae3edd06de7de1dc1dd20de0b6a4c74

**Comment by Mic92** [comment]
The idea of this was to avoid having to do network I/O or take a lock for skipped builds. But I never properly tested how much of a performance difference this makes.

**Pull request merged**
